#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/personal ~/work ~/.config ~/.local ~/dotfiles/.config ~/dotfiles/ ~/learn -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

builtin cd "$selected" || exit
